apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bc16-ingress
  namespace: bc16
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bc16.dev-apps.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: feservice
            port:
              number: 80
  ingressClassName: nginx-bc
